# Generated by Django 4.0.5 on 2022-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
