# Generated by Django 4.0.5 on 2022-07-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_tshirt_slug_alter_tshirt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=200, null=True, unique=True),
        ),
    ]
